### ISSUE TITLE
build_template.sh on a Macintosh

### ISSUE THREAD

**Issue by Larpoux** [coronalabs/submodule-platform-linux#3]
On a Macintosh:
```sh
$ cd corona/platform/linux
$ ./build_template.sh
```
Gives the following error:
Status: Downloaded newer image for coronalabs/linux_builder:latest
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/larpoux/RPiBuildTools.
See 'docker run --help'.
$

**Comment by Shchvova** [comment]
It's basically an unpacked raspbian image used as sysroot for crosscompilation, you can find here: https://drive.google.com/open?id=1ZysxJdDg-XgU3-jshxUPSewTqBYeA7Qq

I would suggest commenting out raspbian related stuff from build_template and build_template_linux
